Django_Meteo_Forecast/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# weather
urlpatterns = [
    path("", include("weather.urls", namespace="weather")),
]

# admin
urlpatterns += [
    path("admin/", admin.site.urls),
]

# Auth and registration
urlpatterns += [
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

weather/urls.py
from django.urls import path
from . import views


app_name = "weather"

urlpatterns = [
    path("", views.welcome, name="welcome"),
    path("home/", views.home, name="home"),
    path('search/', views.search_city, name='search_city'),
    path('autocomplete/', views.autocomplete_city, name='autocomplete_city'),
]

# API
urlpatterns += [
    path(
        "api/search-history/", views.SearchHistoryAPIView.as_view(), name="search-history-api"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

weather/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User


class SearchHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)
    search_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} searched for {self.city} at {self.search_time}"

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
        )

accounts/views.py
# accounts/views.py
from django.shortcuts import redirect

from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView

from django.urls import reverse_lazy
from .forms import SignUpForm


class LoginView(LoginView):
    template_name = "accounts/login.html"


class LogoutView(LogoutView):
    template_name = "accounts/logged_out.html"


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy(
        "accounts:login"
    )  # Redirect to the login page after successful registration
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid


def user_logout(request):
    cache.delete(f'last_viewed_city_{request.user.id}')
    logout(request)
    return redirect('accounts:logout')

weather/views.py
# weather/views.py
from django.shortcuts import render
from django.core.cache import cache
from django.contrib.auth.decorators import login_required
import json

from .models import SearchHistory
from .utils import fetch_weather_data

# API
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import SearchHistorySerializer

from django.http import JsonResponse
from django.views.decorators.http import require_GET


@require_GET
def autocomplete_city(request):
    cities = []
    if "term" in request.GET:
        search_term = request.GET.get("term")
        with open("weather/cities.json", "r") as file:
            cities_data = json.load(file)
        cities = [
            city["name"]
            for city in cities_data
            if search_term.lower() in city["name"].lower()
        ]
    return JsonResponse(cities, safe=False)


@login_required
def home(request):
    with open("weather/cities.json", "r") as file:
        cities = json.load(file)

    city_names = [city["name"] for city in cities]
    latitudes = [city["latitude"] for city in cities]
    longitudes = [city["longitude"] for city in cities]
    weather_data = fetch_weather_data(latitudes, longitudes)
    combined_data = list(zip(city_names, weather_data))

    selected_city = request.GET.get("city")
    if selected_city:
        combined_data = [
            (name, data)
            for name, data in combined_data
            if name.lower() == selected_city.lower()
        ]
        # Store the last viewed city in the cache
        cache.set(f"last_viewed_city_{request.user.id}", selected_city)
        # Save the search history
        SearchHistory.objects.create(user=request.user, city=selected_city)
    else:
        # Retrieve the last viewed city from the cache
        last_viewed_city = cache.get(f"last_viewed_city_{request.user.id}")
        if last_viewed_city:
            combined_data = [
                (name, data)
                for name, data in combined_data
                if name.lower() == last_viewed_city.lower()
            ]
        else:
            # If no city is selected and no city is in the cache, show all cities
            combined_data = list(zip(city_names, weather_data))

    return render(
        request,
        "weather/home.html",
        {"combined_data": combined_data},
    )


def welcome(request):
    with open("weather/cities.json", "r") as file:
        cities = json.load(file)
    city_names = [city["name"] for city in cities]
    print(f"Context variables in welcome view: {city_names}")  # Debug statement
    return render(request, "weather/welcome.html", {"city_names": city_names})


def search_city(request):
    if request.method == "GET":
        city_name = request.GET.get("city")
        if city_name:
            with open("weather/cities.json", "r") as file:
                cities = json.load(file)

            city_names = [city["name"] for city in cities]
            latitudes = [city["latitude"] for city in cities]
            longitudes = [city["longitude"] for city in cities]
            weather_data = fetch_weather_data(latitudes, longitudes)
            combined_data = list(zip(city_names, weather_data))

            filtered_data = [
                (name, data)
                for name, data in combined_data
                if name.lower() == city_name.lower()
            ]

            return render(
                request,
                "weather/home.html",
                {"combined_data": filtered_data, "city_names": city_names},
            )
        else:
            return render(
                request, "weather/home.html", {"combined_data": [], "city_names": []}
            )


class SearchHistoryAPIView(APIView):
    def get(self, request, format=None):
        search_history = SearchHistory.objects.all()
        serializer = SearchHistorySerializer(search_history, many=True)
        return Response(serializer.data)

templates/_base.html
{% load static %}

<html lang="en">

<head>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">


    <!-- Title -->
    <title>{% block title %}Meteo Forecast site{% endblock %}</title>
</head>

<body>
    {% include 'utilities/navbar.html' %}

    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#id_city').on('input', function() {
                var search_term = $(this).val();
                if (search_term.length > 1) {
                    $.get('{% url "weather:autocomplete_city" %}', {term: search_term}, function(data) {
                        var html = '';
                        for (var i = 0; i < data.length; i++) {
                            html += '<div class="autocomplete-item">' + data[i] + '</div>';
                        }
                        $('#autocomplete-list').html(html);
                        $('#autocomplete-list').show();
                    });
                } else {
                    $('#autocomplete-list').html('');
                    $('#autocomplete-list').hide();
                }
            });
    
            $(document).on('click', '.autocomplete-item', function() {
                $('#id_city').val($(this).text());
                $('#autocomplete-list').html('');
                $('#autocomplete-list').hide();
            });
    
            $(document).on('click', function(event) {
                if (!$(event.target).closest('#id_city, #autocomplete-list').length) {
                    $('#autocomplete-list').html('');
                    $('#autocomplete-list').hide();
                }
            });
        });
    </script>
</body>

</html>

templates/accounts/logged_out.html
{% extends "_base.html" %}

{% block content %}

<h1>Logout</h1>

<p>You are now successfully logged out.</p>
<p>Redirecting to the welcome page in <span id="countdown">5</span> seconds...</p>

<script>
    // Function to redirect after a delay
    function redirectAfterDelay(url, delay) {
        setTimeout(function() {
            window.location.href = url;
        }, delay);
    }

    // Function to update the countdown timer
    function updateCountdown(seconds) {
        var countdownElement = document.getElementById('countdown');
        var countdown = seconds;

        var interval = setInterval(function() {
            countdown--;
            countdownElement.textContent = countdown;

            if (countdown <= 0) {
                clearInterval(interval);
                redirectAfterDelay("{% url 'weather:welcome' %}", 0);
            }
        }, 1000);
    }

    // Start the countdown
    updateCountdown(5);
</script>

{% endblock %}

templates/accounts/login.html
{% extends "_base.html" %}


<title>{% block title %}Login{% endblock %}</title>

{% block content %}

<h1>Login</h1>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login">
</form>

{% endblock %}

templates/accounts/signup.html
{% extends "_base.html" %}


<title>{% block title %}Sign up{% endblock %}</title>


{% block content %}

<h1>Sign up</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

{% endblock %}

templates/utilities/navbar.html
<!-- navbar.html -->
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.svg' %}" alt="Logo" width="30" height="24"
                class="d-inline-block align-text-top">
            Weather Forecast
        </a>
        <div class="navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'weather:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'weather:welcome' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url 'weather:search_city' %}" method="GET">
                <input class="form-control me-2" type="search" placeholder="Search city" aria-label="Search"
                    name="city">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
            <div id="autocomplete-list"
                style="display: none; position: absolute; background-color: white; border: 1px solid #ccc; z-index: 1000;">
            </div>
        </div>
    </div>
</nav>
{% endblock navbar %}

templates/weather/city_weather.html
{% extends "_base.html" %}


{% block title %}{{ city.name }}{% endblock %}

{% block content %}

    <h1>{{ city_data.city }} Weather</h1>
    <p>Temperature: {{ city_data.temperature_2m }}</p>
    <p>Relative Humidity: {{ city_data.relative_humidity_2m }}</p>
    <p>Precipitation: {{ city_data.precipitation }}</p>

{% endblock %}

templates/weather/home.html
{% extends "_base.html" %}


{% block content %}
<div class="container-fluid">
    <h1 style="text-align: center;">Welcome to the Weather Home Page</h1>

    <h2>Weather Data</h2>

    {% if not combined_data %}
        <p>No data available for the selected city.</p>
    {% else %}
        {% for city_name, location_data in combined_data %}
        <h3>{{ city_name }}</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="text-center">Max Temperature (°C)</th>
                    <th class="text-center">Min Temperature (°C)</th>
                </tr>
            </thead>
            <tbody>
                {% for day in location_data %}
                <tr>
                    <td>{{ day.date }}</td>
                    <td class="text-center">{{ day.temperature_2m_max }}</td>
                    <td class="text-center">{{ day.temperature_2m_min }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/weather/welcome.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
    <h1>Welcome to the Weather Forecast App</h1>
    <p>Please sign up or log in to view the weather data.</p>
    <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
    <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Log In</a>

    <h2>Available Cities</h2>
    <ul>
        {% for city_name in city_names %}
            <li>{{ city_name }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}